### ISSUE TITLE
SMTP邮箱配置异常

### ISSUE THREAD

**Issue by wznmickey** [DesertsP/Valine-Admin#112]
邮箱连接一直失败。
QQ邮箱的自定义域名邮箱，用了授权码。
[2020-07-20T12:37:41.788017200Z][instance:web1] SMTP邮箱配置异常： Error: Invalid login: 535 Login Fail. Please enter your authorization code to login. More information in http://service.mail.qq.com/cgi-bin/help?subtype=1&&id=28&&no=1001256
[2020-07-20T12:37:41.788068900Z][instance:web1]     at SMTPConnection._formatError (/home/leanengine/app/node_modules/nodemailer/lib/smtp-connection/index.js:605:19)
[2020-07-20T12:37:41.788075800Z][instance:web1]     at SMTPConnection._actionAUTHComplete (/home/leanengine/app/node_modules/nodemailer/lib/smtp-connection/index.js:1340:34)
[2020-07-20T12:37:41.788079900Z][instance:web1]     at SMTPConnection.<anonymous> (/home/leanengine/app/node_modules/nodemailer/lib/smtp-connection/index.js:378:26)
[2020-07-20T12:37:41.788083700Z][instance:web1]     at SMTPConnection._processResponse (/home/leanengine/app/node_modules/nodemailer/lib/smtp-connection/index.js:764:20)
[2020-07-20T12:37:41.788087600Z][instance:web1]     at SMTPConnection._onData (/home/leanengine/app/node_modules/nodemailer/lib/smtp-connection/index.js:570:14)
[2020-07-20T12:37:41.788091400Z][instance:web1]     at TLSSocket.<anonymous> (/home/leanengine/app/node_modules/nodemailer/lib/smtp-connection/index.js:522:47)
[2020-07-20T12:37:41.788095200Z][instance:web1]     at TLSSocket.emit (events.js:315:20)
[2020-07-20T12:37:41.788099000Z][instance:web1]     at addChunk (_stream_readable.js:295:12)
[2020-07-20T12:37:41.788102700Z][instance:web1]     at readableAddChunk (_stream_readable.js:271:9)
[2020-07-20T12:37:41.788106200Z][instance:web1]     at TLSSocket.Readable.push (_stream_readable.js:212:10)
[2020-07-20T12:37:41.788109800Z][instance:web1]     at TLSWrap.onStreamRead (internal/stream_base_commons.js:186:23) {
[2020-07-20T12:37:41.788113700Z][instance:web1]   code: 'EAUTH',
[2020-07-20T12:37:41.788117200Z][instance:web1]   response: '535 Login Fail. Please enter your authorization code to login. More information in http://service.mail.qq.com/cgi-bin/help?subtype=1&&id=28&&no=1001256',
[2020-07-20T12:37:41.788121300Z][instance:web1]   responseCode: 535,
[2020-07-20T12:37:41.788125000Z][instance:web1]   command: 'AUTH PLAIN'

**Comment by suyin-long** [comment]
使用授权码登录：
将`SMTP_PASS`变量的值填写为你邮箱的授权码

**Comment by wznmickey** [comment]
使用qq邮箱的授权码，但是还是有问题。
&nbsp;

——王梓宁（一个来自上海交通大学附属中学闵行分校的学生）


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "苏寅"<notifications@github.com&gt;; 
发送时间: 2020年7月31日(星期五) 上午10:05
收件人: "DesertsP/Valine-Admin"<Valine-Admin@noreply.github.com&gt;; 
抄送: "静静"<wznmickey-chinese@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [DesertsP/Valine-Admin] SMTP邮箱配置异常 (#112)





 
使用授权码登录：
 将SMTP_PASS变量的值填写为你邮箱的授权码

**Comment by wznmickey** [comment]
使用qq邮箱的授权码，但是还是有问题。

**Comment by wznmickey** [comment]
已解决，使用qq邮箱的域名邮箱时USER为QQ号邮箱账号，不能使用自己的域名账号，现在已经配置正常了。谢谢
