### ISSUE TITLE
求助：评论报错

### ISSUE THREAD

**Issue by gkm0** [DesertsP/Valine-Admin#121]
今天部署了评论邮件提醒，测试却发现没有邮件，看日志如下
![QQ浏览器截图20200927115947](https://user-images.githubusercontent.com/33796567/94355851-4c5ccf80-00ba-11eb-909d-2d2b856689ba.png)

我的参数配置如下
![mail-error2](https://user-images.githubusercontent.com/33796567/94355855-567ece00-00ba-11eb-91d8-a6f66f4385d0.png)

哪位大佬来看看这是啥问题
（原来GitHub不能用自己的外链图片啊，还得翻 =。=。）

**Comment by gkm0** [comment]
`[2020-09-27T03:51:09.475544800Z][instance:web1] 这条评论没有 @ 任何人
[2020-09-27T03:51:09.475615000Z][instance:web1] { Error: connect ECONNREFUSED 127.0.0.1:465
[2020-09-27T03:51:09.475624200Z][instance:web1]     at Object.exports._errnoException (util.js:1020:11)
[2020-09-27T03:51:09.475628500Z][instance:web1]     at exports._exceptionWithHostPort (util.js:1043:20)
[2020-09-27T03:51:09.475633200Z][instance:web1]     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1099:14)
[2020-09-27T03:51:09.475637200Z][instance:web1]   code: 'ECONNECTION',
[2020-09-27T03:51:09.475641600Z][instance:web1]   errno: 'ECONNREFUSED',
[2020-09-27T03:51:09.475645700Z][instance:web1]   syscall: 'connect',
[2020-09-27T03:51:09.475649500Z][instance:web1]   address: '127.0.0.1',
[2020-09-27T03:51:09.475654400Z][instance:web1]   port: 465,
[2020-09-27T03:51:09.475660300Z][instance:web1]   command: 'CONN' }`

**Comment by gkm0** [comment]
好了好了，重启一下就好了嘤嘤嘤

**Comment by DesertsP** [comment]
遇到问题可以先重启。over
