### ISSUE TITLE
PARENT_NICK is not defined

### ISSUE THREAD

**Issue by MikoyChinese** [DesertsP/Valine-Admin#25]
LeanEngine: /Comment/afterSave: 500: ReferenceError: PARENT_NICK is not defined
STDERR
    at eval (eval at <anonymous> (/home/leanengine/app/utilities/send-mail.js:40:45), <anonymous>:1:385)
STDERR
    at Object.exports.notice (/home/leanengine/app/utilities/send-mail.js:40:24)
STDERR
    at sendNotification (/home/leanengine/app/cloud.js:10:14)
STDERR
    at /home/leanengine/app/cloud.js:44:12
STDERR
    at err (/home/leanengine/app/node_modules/leanengine/lib/leanengine.js:356:23)
STDERR
    at promiseTry (/home/leanengine/app/node_modules/leanengine/lib/leanengine.js:354:10)
STDERR
    at Promise (/home/leanengine/app/node_modules/leanengine/lib/leanengine.js:249:7)
STDERR
    at callClassHook (/home/leanengine/app/node_modules/leanengine/lib/leanengine.js:237:10)
STDERR
    at promiseTry (/home/leanengine/app/node_modules/leanengine/lib/leanengine.js:104:16)
STDERR
    at err (/home/leanengine/app/node_modules/leanengine/lib/leanengine.js:356:23)
STDERR
    at promiseTry (/home/leanengine/app/node_modules/leanengine/lib/leanengine.js:354:10)
STDERR
    at /home/leanengine/app/node_modules/leanengine/lib/leanengine.js:86:5
STDERR
    at call (/home/leanengine/app/node_modules/connect/index.js:239:7)
STDERR
    at next (/home/leanengine/app/node_modules/connect/index.js:183:5)
STDERR
    at next (/home/leanengine/app/node_modules/connect/index.js:161:14)
STDERR
    at /home/leanengine/app/node_modules/leanengine/middleware/leancloud-headers.js:82:18

**Comment by DesertsP** [comment]
请问是否有自定义邮件通知模板？（MAIL_SUBJECT，MAIL_TEMPLATE等环境变量）

**Comment by MikoyChinese** [comment]
发现问题了，我在博主通知模板中用了PARENT_NICK等不可用变量。
