### ISSUE TITLE
126 邮箱 smtp 连接不上

### ISSUE THREAD

**Issue by wqrqwerqrw** [DesertsP/Valine-Admin#34]
- 错误信息
```
SMTP邮箱配置异常： { Error: Greeting never received
STDOUT web1 21:11:35
    at SMTPConnection._formatError (/home/leanengine/app/node_modules/nodemailer/lib/smtp-connection/index.js:605:19)
STDOUT web1 21:11:35
    at SMTPConnection._onError (/home/leanengine/app/node_modules/nodemailer/lib/smtp-connection/index.js:591:20)
STDOUT web1 21:11:35
    at Timeout._greetingTimeout.setTimeout (/home/leanengine/app/node_modules/nodemailer/lib/smtp-connection/index.js:532:22)
STDOUT web1 21:11:35
    at ontimeout (timers.js:386:11)
STDOUT web1 21:11:35
    at tryOnTimeout (timers.js:250:5)
STDOUT web1 21:11:35
    at Timer.listOnTimeout (timers.js:214:5) code: 'ETIMEDOUT', command: 'CONN' }
```

网上找到的[相关信息](https://blog.csdn.net/q36835109/article/details/53067917)

**Comment by wqrqwerqrw** [comment]
好像找到了方法 SMTP_SECURE 这个变量可以设置..

**Comment by wqrqwerqrw** [comment]
- 自定义邮件服务器地址和端口信息，删除SMTP_SERVICE环境变量，新增以下变量：

SMTP_HOST | smtp.qq.com | [可选]SMTP_SERVICE留空时，自定义SMTP服务器地址
-- | -- | --
SMTP_PORT | 465 | [可选]SMTP_SERVICE留空时，自定义SMTP端口
SMTP_SECURE | true | [可选]SMTP_SERVICE留空时填写

- 126 `SMTP_SECURE` 要手动添加为true

**Comment by DesertsP** [comment]
使用自定义的SMTP是否能够解决问题?

**Comment by wqrqwerqrw** [comment]
> 使用自定义的SMTP是否能够解决问题?

可以的 改smtp-secure就行了

**Comment by wqrqwerqrw** [comment]
> 使用自定义的SMTP是否能够解决问题?

过了一段时间又出现了这个错误, 好魔幻

**Comment by wqrqwerqrw** [comment]
> 使用自定义的SMTP是否能够解决问题?

修改完 `smtp_secure` 后出现这个错误好像是和频率有关, 频率低就不会出现错误了

**Comment by wqrqwerqrw** [comment]
> > 使用自定义的SMTP是否能够解决问题?
> 
> 修改完 `smtp_secure` 后出现这个错误好像是和频率有关, 频率低就不会出现错误了

126频率限制大概在3分钟左右

**Comment by DesertsP** [comment]
> > > 使用自定义的SMTP是否能够解决问题?
> > 
> > 
> > 修改完 `smtp_secure` 后出现这个错误好像是和频率有关, 频率低就不会出现错误了
> 
> 126频率限制大概在3分钟左右

看起来你已经找到问题所在了
