### ISSUE TITLE
SMTP配置永远报错,自闭了

### ISSUE THREAD

**Issue by wolfdan666** [DesertsP/Valine-Admin#65]
![image](https://user-images.githubusercontent.com/37760924/66112829-27946000-e5fe-11e9-8eb9-f88efcadb906.png)

**Comment by wolfdan666** [comment]
![image](https://user-images.githubusercontent.com/37760924/66113412-4b0bda80-e5ff-11e9-9df6-9754b396205a.png)
https://github.com/DesertsP/Valine-Admin/issues/54

**Comment by wolfdan666** [comment]
成功了,谢谢大佬在  https://github.com/DesertsP/Valine-Admin/issues/54  已经回答

**Comment by MaskXman** [comment]
同样error 535，#54没解决怎么办

**Comment by MaskXman** [comment]
![image](https://user-images.githubusercontent.com/59054903/77987773-4ecdaf00-734d-11ea-8357-b192fb97a191.png)

**Comment by colingpt** [comment]
真的是令人自闭 :cry:

126 163 hotmail 都试过了。。。 
126和163报错550：
```
Node app is running on port: 3000
[2020-04-28T07:21:45.109Z][system] 实例启动成功：{"runtime":"nodejs-v12.16.2","version":"3.3.2"}
[2020-04-28T07:21:45.167Z][system] 正在更新云函数信息 ...
[2020-04-28T07:21:45.192Z][system] 部署完成：1 个实例部署成功
[2020-04-28T07:21:46.239766895Z][instance:web1] SMTP邮箱配置正常！
[2020-04-28T07:22:34.598381209Z][instance:web1] IP: xx.xx.xx.xx
[2020-04-28T07:22:34.606198329Z][instance:web1] 这条评论没有 @ 任何人
[2020-04-28T07:22:34.702140023Z][instance:web1] 垃圾评论检测完成，放行~
[2020-04-28T07:22:36.729520442Z][instance:web1] Error: Mail command failed: 550 Invalid User
[2020-04-28T07:22:36.729595299Z][instance:web1]     at SMTPConnection._formatError (/home/leanengine/app/node_modules/nodemailer/lib/smtp-connection/index.js:605:19)
[2020-04-28T07:22:36.729625444Z][instance:web1]     at SMTPConnection._actionMAIL (/home/leanengine/app/node_modules/nodemailer/lib/smtp-connection/index.js:1370:34)
[2020-04-28T07:22:36.729646356Z][instance:web1]     at SMTPConnection.<anonymous> (/home/leanengine/app/node_modules/nodemailer/lib/smtp-connection/index.js:857:18)
[2020-04-28T07:22:36.72966501Z][instance:web1]     at SMTPConnection._processResponse (/home/leanengine/app/node_modules/nodemailer/lib/smtp-connection/index.js:764:20)
[2020-04-28T07:22:36.729680577Z][instance:web1]     at SMTPConnection._onData (/home/leanengine/app/node_modules/nodemailer/lib/smtp-connection/index.js:570:14)
[2020-04-28T07:22:36.729697163Z][instance:web1]     at TLSSocket.<anonymous> (/home/leanengine/app/node_modules/nodemailer/lib/smtp-connection/index.js:522:47)
[2020-04-28T07:22:36.729715327Z][instance:web1]     at TLSSocket.emit (events.js:310:20)
[2020-04-28T07:22:36.729729947Z][instance:web1]     at addChunk (_stream_readable.js:286:12)
[2020-04-28T07:22:36.729745404Z][instance:web1]     at readableAddChunk (_stream_readable.js:268:9)
[2020-04-28T07:22:36.729760736Z][instance:web1]     at TLSSocket.Readable.push (_stream_readable.js:209:10)
[2020-04-28T07:22:36.729772222Z][instance:web1]     at TLSWrap.onStreamRead (internal/stream_base_commons.js:186:23) {
[2020-04-28T07:22:36.729796733Z][instance:web1]   code: 'EENVELOPE',
[2020-04-28T07:22:36.729807413Z][instance:web1]   response: '550 Invalid User',
[2020-04-28T07:22:36.729817268Z][instance:web1]   responseCode: 550,
[2020-04-28T07:22:36.729827481Z][instance:web1]   command: 'MAIL FROM'
[2020-04-28T07:22:36.729837486Z][instance:web1] }
```

hotmail 报错501：
```
部署完成：1 个实例部署成功
[2020-04-28T06:43:17.252182423Z][instance:web1] SMTP邮箱配置正常！
[2020-04-28T06:44:46.000000000Z][instance:web1] IP: xxx
[2020-04-28T06:44:46.23463503Z][instance:web1] IP: xxx
[2020-04-28T06:44:46.246742309Z][instance:web1] 这条评论没有 @ 任何人
[2020-04-28T06:44:46.328587878Z][instance:web1] 垃圾评论检测完成，放行~
[2020-04-28T06:44:47.000000000Z][instance:web1]     at SMTPConnection._processResponse (/home/leanengine/app/node_modules/nodemailer/lib/smtp-connection/index.js:764:20)
[2020-04-28T06:44:47.512535861Z][instance:web1] Error: Mail command failed: 501 5.1.7 Invalid address
[2020-04-28T06:44:47.512619115Z][instance:web1]     at SMTPConnection._formatError (/home/leanengine/app/node_modules/nodemailer/lib/smtp-connection/index.js:605:19)
[2020-04-28T06:44:47.512644282Z][instance:web1]     at SMTPConnection._actionMAIL (/home/leanengine/app/node_modules/nodemailer/lib/smtp-connection/index.js:1370:34)
[2020-04-28T06:44:47.512657734Z][instance:web1]     at SMTPConnection.<anonymous> (/home/leanengine/app/node_modules/nodemailer/lib/smtp-connection/index.js:857:18)
[2020-04-28T06:44:47.51267218Z][instance:web1]     at SMTPConnection._processResponse (/home/leanengine/app/node_modules/nodemailer/lib/smtp-connection/index.js:764:20)
[2020-04-28T06:44:47.512685882Z][instance:web1]     at SMTPConnection._onData (/home/leanengine/app/node_modules/nodemailer/lib/smtp-connection/index.js:570:14)
[2020-04-28T06:44:47.512698738Z][instance:web1]     at TLSSocket.<anonymous> (/home/leanengine/app/node_modules/nodemailer/lib/smtp-connection/index.js:710:55)
[2020-04-28T06:44:47.512711477Z][instance:web1]     at TLSSocket.emit (events.js:310:20)
[2020-04-28T06:44:47.512723381Z][instance:web1]     at addChunk (_stream_readable.js:286:12)
[2020-04-28T06:44:47.512735181Z][instance:web1]     at readableAddChunk (_stream_readable.js:268:9)
[2020-04-28T06:44:47.512747167Z][instance:web1]     at TLSSocket.Readable.push (_stream_readable.js:209:10)
[2020-04-28T06:44:47.512759302Z][instance:web1]     at TLSWrap.onStreamRead (internal/stream_base_commons.js:186:23) {
[2020-04-28T06:44:47.512771582Z][instance:web1]   code: 'EENVELOPE',
[2020-04-28T06:44:47.512783093Z][instance:web1]   response: '501 5.1.7 Invalid address',
[2020-04-28T06:44:47.512795207Z][instance:web1]   responseCode: 501,
[2020-04-28T06:44:47.512806771Z][instance:web1]   command: 'MAIL FROM'
[2020-04-28T06:44:47.512818599Z][instance:web1] }
```

都是开了三方独立密码的。。。

相关配置：

```
SMTP_SERVICE: 163
SMTP_USER: xx@163.com
SMTP_PASS: 生成的密码
SENDER_NAME： aaaa
```

自闭求救。。。

**Comment by bufx** [comment]
> 同样error 535，#54没解决怎么办
如果是谷歌邮箱的话：
可能需要允许访问您的Gmail帐户。

https://accounts.google.com/b/0/DisplayUnlockCaptcha
