### ISSUE TITLE
邮件提醒报错500

### ISSUE THREAD

**Issue by edmundwsy** [DesertsP/Valine-Admin#67]
遇到邮件提醒报错

LeanEngine: /Comment/afterSave: 500: SyntaxError: Unexpected token ILLEGALL

SMTP配置成功，Akismet key 未配置

**Comment by edmundwsy** [comment]
```
web1 15:00:39
SMTP邮箱配置正常！
STDOUT web1 15:08:16
IP: 10.10.94.39
STDOUT web1 15:08:17
被@者匿名，不会发送通知
STDOUT web1 15:08:19
Akismet key 异常!
STDOUT web1 15:10:54
IP: 10.10.94.39
STDOUT web1 15:10:54
这条评论没有 @ 任何人
STDOUT web1 15:10:58
Akismet key 异常!
STDERR web1 15:11:15
LeanEngine: /Comment/afterSave: 500: SyntaxError: Unexpected token ILLEGAL
STDERR web1 15:11:15
    at Object.exports.notice (/home/leanengine/app/utilities/send-mail.js:39:44)
STDERR web1 15:11:15
    at sendNotification (/home/leanengine/app/cloud.js:10:14)
STDERR web1 15:11:15
    at /home/leanengine/app/cloud.js:44:12
STDERR web1 15:11:15
    at err (/home/leanengine/app/node_modules/leanengine/lib/leanengine.js:368:23)
STDERR web1 15:11:15
    at promiseTry (/home/leanengine/app/node_modules/leanengine/lib/leanengine.js:366:10)
STDERR web1 15:11:15
    at Promise (/home/leanengine/app/node_modules/leanengine/lib/leanengine.js:253:7)
STDERR web1 15:11:15
    at callClassHook (/home/leanengine/app/node_modules/leanengine/lib/leanengine.js:241:10)
STDERR web1 15:11:15
    at promiseTry (/home/leanengine/app/node_modules/leanengine/lib/leanengine.js:104:16)
STDERR web1 15:11:15
    at err (/home/leanengine/app/node_modules/leanengine/lib/leanengine.js:368:23)
STDERR web1 15:11:15
    at promiseTry (/home/leanengine/app/node_modules/leanengine/lib/leanengine.js:366:10)
STDERR web1 15:11:15
    at /home/leanengine/app/node_modules/leanengine/lib/leanengine.js:86:5
STDERR web1 15:11:15
    at call (/home/leanengine/app/node_modules/connect/index.js:239:7)
STDERR web1 15:11:15
    at next (/home/leanengine/app/node_modules/connect/index.js:183:5)
STDERR web1 15:11:15
    at next (/home/leanengine/app/node_modules/connect/index.js:161:14)
STDERR web1 15:11:15
    at /home/leanengine/app/node_modules/leanengine/middleware/leancloud-headers.js:82:18
STDERR web1 15:11:15
    at call (/home/leanengine/app/node_modules/connect/index.js:239:7)
```

**Comment by shanlanCoding** [comment]
贴变量的配置截图。

**Comment by MironChen** [comment]
遇到同样的问题
