### ISSUE TITLE
定时任务配置了30分钟仍然整点执行

### ISSUE THREAD

**Issue by lianlilin** [DesertsP/Valine-Admin#83]
配置了之后看服务器的运行日志有报错，求解……

[2020-03-13T08:01:07.107642543Z][instance:web1] LeanEngine: /self_wake: 500: Error: undefined is not a valid uri or options object.
[2020-03-13T08:01:07.107682914Z][instance:web1] at request (/home/leanengine/app/node_modules/request/index.js:44:11)
[2020-03-13T08:01:07.107697927Z][instance:web1] at /home/leanengine/app/cloud.js:69:5
[2020-03-13T08:01:07.107709216Z][instance:web1] at promiseTry.then.user (/home/leanengine/app/node_modules/leanengine/lib/leanengine.js:202:14)
[2020-03-13T08:01:07.107720993Z][instance:web1] at process.tickCallback (internal/process/nexttick.js:109:7)
[2020-03-13T08:01:07.110Z][system] CloudQueue 运行失败 1326005e-77a0-4c6e-9d8e-df1144b32527: self_wake !! {“error”:”500 - {"code":1,"error":"undefined is not a valid uri or options object."}”}

像是定时任务没拿到参数的样子，配置参数如下：
![image](https://user-images.githubusercontent.com/17775741/76603534-16099980-6548-11ea-81a3-bf8bde975cc0.png)

**Comment by lianlilin** [comment]
自己回答一下，重启服务解决。新的问题，定时任务虽然设置了30分钟启动一次，但是好像还是1个小时执行一次？

**Comment by 0x2E** [comment]
@lianlilin 定时任务改成 `0 */30 7-23 * * ?`  [cron定时任务解析出错](https://forum.leancloud.cn/t/cron/20365)

**Comment by lianlilin** [comment]
> 0 */30 7-23 * * ?

非常感谢，修改定时任务后需要重启服务吗？为什么要这么修改呢？我看之前的写法下面提示显示也是30分钟执行一次。

**Comment by 0x2E** [comment]
我重新启动了。
我的理解是这样的： 0/30 意思是从第 0 分钟开始，每 30 分钟执行一次，\*/30 意思是从定时任务设置完成开始，每 30 分钟执行一次。假设你 8:06 设置好了定时任务，那么 0/30 的会在 8:30 运行，\*/30 的会在 8:36 运行。
至于为什么 0/30 在 Leancloud 的后端被解析成每小时执行，我也不清楚了。

**Comment by lianlilin** [comment]
> 我重新启动了。
> 我的理解是这样的： 0/30 意思是从第 0 分钟开始，每 30 分钟执行一次，*/30 意思是从定时任务设置完成开始，每 30 分钟执行一次。假设你 8:06 设置好了定时任务，那么 0/30 的会在 8:30 运行，*/30 的会在 8:36 运行。
> 至于为什么 0/30 在 Leancloud 的后端被解析成每小时执行，我也不清楚了。

非常感谢，你的方案亲测好用。
